###
# @name=addUser
POST http://{{host}}:8089/users
Content-Type: application/json

{
  "user_name": "test{{$randomInt}}",
  "gender": 1,
  "age": 22,
  "submit_time": "{{$timestamp}}"
}

###
# @name=addBook
POST http://{{host}}:8089/books
Content-Type: application/json

{
  "book_name": "testbook",
  "author_id": 1
}

###
# @name=showUsers
GET http://{{host}}:8089/users
Accept: application/json

###
# @name=showBooks
GET http://{{host}}:8089/books
Accept: application/json

###
# @name=showUserById
GET http://{{host}}:8089/users/8
Accept: application/json

###
# @name=deleteUserById
DELETE http://{{host}}:8089/users/9
Accept: application/json

###
# @name=updateUserById
PUT http://{{host}}:8089/users/8
Content-Type: application/json

{
  "user_name": "demo"
}

###
# @name=showUsersByName
GET http://{{host}}:8089/users
Accept: application/json
Content-Type: application/json

{
  "user_name": "demo"
}

###
# @name=showUsersByName
GET http://{{host}}:8089/users?user_name=demo
Accept: application/json

###

