POST http://localhost:8089/users
Content-Type: application/json

{
  "username": "test"
}

###
POST http://localhost:8089/books
Content-Type: application/json

{
  "bookname": "testbook",
  "author_id": 1
}

###

GET http://localhost:8089/users
Accept: application/json

###

GET http://localhost:8089/books
Accept: application/json

###
