###
# @name=addPatient
POST http://{{host}}:8089/patients
Content-Type: application/json

{
  "user_name": "test{{$randomInt}}",
  "gender": 1,
  "age": 22
}

###
# @name=addBook
POST http://{{host}}:8089/books
Content-Type: application/json

{
  "book_name": "testbook",
  "author_id": 1
}

###
# @name=showPatients
GET http://{{host}}:8089/patients
Accept: application/json

###
# @name=showBooks
GET http://{{host}}:8089/books
Accept: application/json

###
# @name=showPatientById
GET http://{{host}}:8089/patients/8
Accept: application/json

###
# @name=deletePatientById
DELETE http://{{host}}:8089/patients/9
Accept: application/json

###
# @name=updatePatientById
PUT http://{{host}}:8089/patients/8
Content-Type: application/json

{
  "user_name": "demo"
}

###
# @name=showPatientsByName
GET http://{{host}}:8089/patients
Accept: application/json
Content-Type: application/json

{
  "user_name": "demo"
}

###
# @name=showPatientsByName
GET http://{{host}}:8089/patients?user_name=demo
Accept: application/json

###

