name: first-github-action
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello 
        run: echo 'Hello world!!!'
      - name: ls 
        run: ls -hl ${{ github.workspace }}
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: ""
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          EXCLUDE: "/dist/, /node_modules/"
