name: first-github-action
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Hello 
        run: echo 'Hello world!!!'
      - uses: actions/checkout@v3
      - name: ls 
        run: ls -hl ${{ github.workspace }}
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
          EXCLUDE: "/dist/, /node_modules/"
      - name: Update Server
        uses: fifsky/ssh-action@master
        with:
          command: |
            kill -9 $(lsof -t -i:8089)
          host: ${{ secrets.REMOTE_HOST }}
          user: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY}}

